name: notion2hugo
on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小时拉取一次
  workflow_dispatch: ~

jobs:
  sync:
    name: notion to hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true   # 递归拉取子模块，比如 Hugo 主题
          fetch-depth: 0     # 拉取完整提交历史

      - name: Notion-site
        uses: pkwenda/notion-site@master   # 拉取 Notion 数据并转换成 Markdown
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}

      - name: Reformat bookmark shortcodes using sed
        run: |
          echo "Processing markdown files to reformat bookmark shortcodes..."
          # 查找 content 目录下所有 .md 文件
          # 使用 sed 命令在每个文件中查找形如 {{< bookmark ... >}}
          # 然后将其替换为块级格式，即在其后添加固定文本和闭合标签
          find content -type f -name "*.md" -exec sed -i 's@{{<\s*bookmark\([^>]*\)>}}@{{< bookmark\1 >}}\n点击查看详情\n{{< /bookmark >}}@g' {} \;

      - name: Check if there are any changes
        id: verify_diff
        run: |
          if [ -n "$(git status -s .)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "sync articles from notion and reformat bookmark shortcode"
          git config pull.rebase false
          git pull
          git push
