name: notion2hugo
on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小时拉取一次
  workflow_dispatch: ~

jobs:
  sync:
    name: notion to hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true         # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0           # Fetch all history for .GitInfo and .Lastmod

      - name: Notion-site
        uses: pkwenda/notion-site@master    # 拉取 Notion database 并转换成 Markdown
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}

      - name: Reformat bookmark shortcodes
        run: |
          echo "Reformatting bookmark shortcodes to the desired multi-line format..."
          # 针对 content 文件夹下所有的 Markdown 文件
          # 原来遇到的问题一般为：{{< bookmark ... >}}
          # 此 sed 命令将其替换为：
          # {{< bookmark ... >}}
          # 点击查看详情
          # {{< /bookmark >}}
          find content -type f -name "*.md" -exec sed -i 's/{{<\s*bookmark\([^>]*\)>}}/{{< bookmark\1 >}}\n点击查看详情\n{{< \/bookmark >}}/g' {} \;

      - name: Check if there are any changes
        id: verify_diff
        run: |
          [ -z "$(git status -s .)" ] || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "sync article from notion"
          git config pull.rebase false
          git pull
          git push
